# Note: This is a composite GitHub Actions, it should do all env setup, caching an so on, so other pipelines can just compose their own stuff on top of that.
# Docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Deploy Website to CF
description: Shared configuration for deploying website to Cloudflare Pages
inputs:
  websiteDirectory:
    description: Build script for building the website
    required: false
    default: website
  buildScript:
    description: Build script for building the website
    required: true
  cloudflareApiToken:
    description: CF API Token
    required: true
  cloudflareAccountId:
    description: CF API Account ID
    required: true
  githubToken:
    description: GH PAT
    required: true
  projectName:
    description: CF Pages Project name
    required: true
  artifactDir:
    description: Artifact dir after build and export
    required: false
    default: out
  prId:
    description: PR id for publishing preview
    required: false
    default: ''
  commentId:
    description: ID to use for the comment
    required: false
    default: website_deployment
  commentTitle:
    description: Title to use for the PR comment
    required: false
    default: 💻 Website Preview
  mainBranch:
    description: The main branch name that is set in CF Pages
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: build website
      shell: bash
      run: ${{ inputs.buildScript }}
      working-directory: ${{ inputs.websiteDirectory }}

    - name: fix wildcard redirects
      shell: bash
      # NextJS requires "docs/things/:path*" syntax, but that does not work on Cloudflare.
      # Redirects in CF uses "*" and ":splat".
      # With ":path*" the redirect from "docs/old/:path*" to "docs/new/:path*" becomes "docs/new/foo*"
      # - /docs/integrations/:path* /docs/other-integrations/:path* 302
      # + /docs/integrations/* /docs/other-integrations/:splat 302
      run: |
        if [ -f _redirects ]; then
          sed -i 's|\([^ ]*\):path\* \([^ ]*\):path\* \([0-9]*\)|\1* \2:splat \3|' _redirects
        fi
      working-directory: ${{ format('{0}/{1}', inputs.websiteDirectory, inputs.artifactDir) }}

    - name: push to cloudflare pages
      uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
      id: deploy
      with:
        apiToken: ${{ inputs.cloudflareApiToken }}
        accountId: ${{ inputs.cloudflareAccountId }}
        command: |
          pages deploy ${{ format('{0}/{1}', inputs.websiteDirectory, inputs.artifactDir) }} --project-name=${{ inputs.projectName }} --branch=${{ inputs.prId != '' && format('pr-{0}', inputs.prId) || inputs.mainBranch }}
        gitHubToken: ${{ inputs.githubToken }}

    - name: find pr comment
      uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
      id: fc
      if: ${{ inputs.prId != '' }}
      with:
        token: ${{ inputs.githubToken }}
        issue-number: ${{ inputs.prId }}
        comment-author: 'github-actions[bot]'
        body-includes: <!--- ${{ inputs.commentId }} --->

    - name: create/update comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      if: ${{ inputs.prId != '' }}
      with:
        token: ${{ inputs.githubToken }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ inputs.prId }}
        body: |
          <!--- ${{ inputs.commentId }} --->
          ### ${{ inputs.commentTitle }}

          The latest changes are available as preview in: [${{ steps.deploy.outputs.url }}](${{ steps.deploy.outputs.url }})
        edit-mode: replace
