# Note: This is a composite GitHub Actions, it should do all env setup, caching an so on, so other pipelines can just compose their own stuff on top of that.
# Docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Deploy Website to CF
description: Shared configuration for deploying website to Cloudflare Pages
inputs:
  websiteDirectory:
    description: Build script for building the website
    required: false
    default: website
  buildScript:
    description: Build script for building the website
    required: true
  cloudflareApiToken:
    description: CF API Token
    required: true
  cloudflareAccountId:
    description: CF API Account ID
    required: true
  githubToken:
    description: GH PAT
    required: true
  projectName:
    description: CF Pages Project name
    required: true
  artifactDir:
    description: Artifact dir after build and export
    required: false
    default: out
  prId:
    description: PR id for publishing preview
    required: false
    default: ''
  commentId:
    description: ID to use for the comment
    required: false
    default: website_deployment
  commentTitle:
    description: Title to use for the PR comment
    required: false
    default: 💻 Website Preview
  mainBranch:
    description: The main branch name that is set in CF Pages
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: build website
      env:
        NEXT_PUBLIC_ALGOLIA_INDEX_NAME: searchv2_main
        NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: a5522203ca95675199cc21edf09e6d75
        NEXT_PUBLIC_ALGOLIA_APP_ID: ANRJKXZTRW
      shell: bash
      run: ${{ inputs.buildScript }}
      working-directory: ${{ inputs.websiteDirectory }}

    - name: push to cloudflare pages
      uses: cloudflare/pages-action@v1.5.0
      id: deploy
      with:
        apiToken: ${{ inputs.cloudflareApiToken }}
        accountId: ${{ inputs.cloudflareAccountId }}
        projectName: ${{ inputs.projectName }}
        directory: ${{ format('{0}/{1}', inputs.websiteDirectory, inputs.artifactDir) }}
        branch: ${{ inputs.prId != '' && format('pr-{0}', inputs.prId) || inputs.mainBranch }}

    - name: find pr comment
      uses: peter-evans/find-comment@v3
      id: fc
      if: ${{ inputs.prId != '' }}
      with:
        token: ${{ inputs.githubToken }}
        issue-number: ${{ inputs.prId }}
        comment-author: 'github-actions[bot]'
        body-includes: <!--- ${{ inputs.commentId }} --->

    - name: create/update comment
      uses: peter-evans/create-or-update-comment@v3
      if: ${{ inputs.prId != '' }}
      with:
        token: ${{ inputs.githubToken }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ inputs.prId }}
        body: |
          <!--- ${{ inputs.commentId }} ---> 
          ### ${{ inputs.commentTitle }}

          The latest changes are available as preview in: [${{ steps.deploy.outputs.url }}](${{ steps.deploy.outputs.url }})
        edit-mode: replace
