name: 'Guild Release Trackback'
description: 'Utility to track back a release to a PR, and notify in case of a breaking change'
author: 'The Guild'
inputs:
  jobStatus:
    required: true
    description: 'the job status'
    default: ${{ job.status }}
  prOwners:
    required: true
    description: 'list of gh logins that are considered relevant for this action, use JSON string'
    default: renovate[bot]
  prereleaseTag:
    required: true
    description: 'list of NPM prerelease tags matchers'
    default: 'rc-*'
  relevantPackages:
    required: true
    description: 'list of packages, wildcard is supported'
    default: ''
  token:
    required: false
    description: 'github token'
runs:
  using: 'node16'
  main: 'dist/index.js'
