# Note: This is a composite GitHub Actions, it should do all env setup, caching an so on, so other pipelines can just compose their own stuff on top of that.
# Docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Setup
description: |
  Shared configuration for setting up The Guild's usual environent. It sets up node, detects defined "packageManager", enables corepack and installs with the specified package manager.

# make sure to match the inputs for all workflows using this action
inputs:
  node-version:
    type: string
    description: Node.js version to use.
    required: false
  node-version-file:
    type: string
    description: File containing the version to use.
    required: false
  working-directory:
    type: string
    description: Working directory.
    required: false
    default: .
  install-command:
    type: string
    description: Custom install command to run after the environment has been set up. Will run instead of the default "install" step.
    required: false

outputs:
  package-manager:
    description: The detected package manager that is used.
    value: ${{ steps.pkgmngr.outputs.result }}

runs:
  using: composite
  steps:
    - name: cancel concurrent runs
      uses: styfle/cancel-workflow-action@0.12.1
      continue-on-error: true
      with:
        access_token: ${{ github.token }}
    - name: detect package manager
      id: pkgmngr
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const wd = '${{ inputs.working-directory }}';
          const pkgPath = wd ? `./${wd}/package.json` : 'package.json';
          let { packageManager } = require(pkgPath);
          if (!packageManager && wd) {
            // try the packageManager from root package json
            packageManager = require('package.json').packageManager;
          }
          if (!packageManager) {
            return core.setFailed(`"packageManager" not defined in "${pkgPath}". Please choose a package manager with "corepack use <your favourite manager>".`);
          }
          const [name] = packageManager.split('@');
          console.log(name);
          return name;
    - name: enable corepack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: corepack enable
    - name: set up node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}
        cache: ${{ steps.pkgmngr.outputs.result }}
    - name: install
      if: inputs.install-command == ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: >
        ${{ steps.pkgmngr.outputs.result }} install
        ${{ steps.pkgmngr.outputs.result == 'pnpm' && '--frozen-lockfile' || '' }}
        ${{ steps.pkgmngr.outputs.result == 'yarn' && '--immutable' || '' }}
    - name: custom install
      if: inputs.install-command != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.install-command }}