# Note: This is a composite GitHub Actions, it should do all env setup, caching an so on, so other pipelines can just compose their own stuff on top of that.
# Docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Configure Environment
description: Shared configuration for checkout, Node.js and package manager
inputs:
  nodeVersion:
    description: Node.js version to use
    required: true
    default: '18'
  workingDirectory:
    description: Working directory
    required: false
    default: ./
  packageManager:
    description: Package manager
    required: false
    default: yarn
runs:
  using: composite
  steps:
    - name: Setup ${{ inputs.packageManager }}
      id: pnpm_setup
      if: inputs.packageManager == 'pnpm'
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.18.1 
        run_install: false

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: ${{ inputs.packageManager }}
        cache-dependency-path: |
          **/pnpm-lock.yaml
          **/yarn.lock
          patches/**

    - name: yarn install
      shell: bash
      if: inputs.packageManager == 'yarn'
      run: yarn install --ignore-engines --frozen-lockfile --immutable
      working-directory: ${{ inputs.workingDirectory }}

    - name: pnpm install
      shell: bash
      if: inputs.packageManager == 'pnpm'
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.workingDirectory }}
