# Note: this pipelines is for the `shared-config` library

name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  dependencies:
    uses: ./.github/workflows/changesets-dependencies.yaml
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  alpha:
    uses: ./.github/workflows/release-snapshot.yml
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 22
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}

  rc:
    uses: ./.github/workflows/release-snapshot.yml
    if: ${{ github.event.pull_request.title == 'Upcoming Release Changes' }}
    with:
      npmTag: rc
      buildScript: build
      nodeVersion: 22
      packageManager: pnpm
      restoreDeletedChangesets: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
