# Note: this pipelines is for the `shared-config` library

name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  dependencies:
    uses: ./.github/workflows/changesets-dependencies.yaml
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: ./.github/workflows/release-snapshot.yml
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
